`timescale 1ns/1ps

// Testbench for the cache subsystem.
// Reads a trace file (format: "addr is_write [write_byte]" per line,
// hex values) generated by tb/trace_generator.py, drives the
// cache_controller with each access in sequence (waiting for busy to
// clear between requests), and tracks hit/miss/writeback counts.
//
// At the end, these RTL-observed stats are compared against golden
// model stats (computed independently by tb/cache_model_golden.py and
// written to a companion "<trace>_golden_stats.txt" file by
// sim/run_full_sim.sh before this simulation runs) - this checks the
// RTL's cache behavior against golden truth, not just that "it ran".
//
// TRACE_FILE / GOLDEN_FILE are elaboration-time parameters, overridden
// per-trace via `xelab -generic_top` in sim/run_full_sim.sh (chosen
// over runtime plusargs after this xsim version proved unreliable at
// parsing -testplusarg from the command line).
module cache_tb;

    import cache_config_pkg::*;

        parameter ADDR_WIDTH = 32;
    `include "trace_select.svh"
    reg clk;
    reg rst_n;

    reg                   req_valid;
    reg                   req_is_write;
    reg  [ADDR_WIDTH-1:0] req_addr;
    reg  [7:0]             req_wdata;

    wire                  resp_valid;
    wire                  resp_hit;
    wire [7:0]             resp_rdata;
    wire                  busy;

    wire                  stat_hit_pulse;
    wire                  stat_miss_pulse;
    wire                  stat_writeback_pulse;

    integer rtl_hits, rtl_misses, rtl_writebacks, rtl_accesses;

    cache_controller #(
        .ADDR_WIDTH(ADDR_WIDTH),
        .NUM_SETS(NUM_SETS),
        .ASSOCIATIVITY(ASSOCIATIVITY),
        .LINE_SIZE_BYTES(LINE_SIZE_BYTES),
        .TAG_BITS(TAG_BITS),
        .INDEX_BITS(INDEX_BITS),
        .OFFSET_BITS(OFFSET_BITS),
        .WAY_BITS(WAY_BITS),
        .WRITE_BACK(WRITE_BACK),
        .MISS_PENALTY_CYCLES(MISS_PENALTY_CYCLES),
        .WRITEBACK_PENALTY_CYCLES(WRITEBACK_PENALTY_CYCLES)
    ) dut (
        .clk(clk), .rst_n(rst_n),
        .req_valid(req_valid), .req_is_write(req_is_write),
        .req_addr(req_addr), .req_wdata(req_wdata),
        .resp_valid(resp_valid), .resp_hit(resp_hit), .resp_rdata(resp_rdata),
        .busy(busy),
        .stat_hit_pulse(stat_hit_pulse),
        .stat_miss_pulse(stat_miss_pulse),
        .stat_writeback_pulse(stat_writeback_pulse)
    );

    always #10 clk = ~clk;

    initial begin
        $dumpfile("waveforms.vcd");
        $dumpvars(0, cache_tb);
    end

    // Accumulate stats from the controller's event pulses
    always @(posedge clk) begin
        if (!rst_n) begin
            rtl_hits <= 0;
            rtl_misses <= 0;
            rtl_writebacks <= 0;
            rtl_accesses <= 0;
        end else begin
            if (stat_hit_pulse)  rtl_hits <= rtl_hits + 1;
            if (stat_miss_pulse) rtl_misses <= rtl_misses + 1;
            if (stat_writeback_pulse) rtl_writebacks <= rtl_writebacks + 1;
        end
    end

    // Task: apply one access, wait for it to complete (resp_valid pulses
    // once the request is fully serviced, whether hit or resolved miss)
    task automatic apply_access;
        input [ADDR_WIDTH-1:0] addr;
        input                  is_write;
        input [7:0]             wdata;
        begin
            @(negedge clk);
            wait (!busy);
            req_valid    = 1'b1;
            req_is_write = is_write;
            req_addr     = addr;
            req_wdata    = wdata;
            @(negedge clk);
            req_valid = 1'b0;
            wait (resp_valid);
            @(negedge clk);
        end
    endtask

    // Trace file reading
    integer file_handle;
    integer scan_count;
    integer file_addr, file_is_write, file_wbyte;

    integer golden_hits, golden_misses, golden_writebacks, golden_accesses;
    integer stats_file_handle;

    initial begin
        clk   = 0;
        rst_n = 0;
        req_valid = 0;
        req_is_write = 0;
        req_addr = 0;
        req_wdata = 0;
        rtl_accesses = 0;

        #20;
        rst_n = 1;
        #20;

        $display("=== Running trace: %s ===", TRACE_FILE);

        file_handle = $fopen(TRACE_FILE, "r");
        if (file_handle == 0) begin
            $display("ERROR: could not open trace file %s", TRACE_FILE);
            $finish;
        end

        while (!$feof(file_handle)) begin
            scan_count = $fscanf(file_handle, "%h %d", file_addr, file_is_write);
            if (scan_count == 2) begin
                if (file_is_write) begin
                    scan_count = $fscanf(file_handle, " %h\n", file_wbyte);
                    apply_access(file_addr[ADDR_WIDTH-1:0], 1'b1, file_wbyte[7:0]);
                end else begin
                    apply_access(file_addr[ADDR_WIDTH-1:0], 1'b0, 8'd0);
                end
                rtl_accesses = rtl_accesses + 1;
            end
        end
        $fclose(file_handle);

        $display("----------------------------------------");
        $display("RTL STATS: accesses=%0d hits=%0d misses=%0d writebacks=%0d",
                   rtl_accesses, rtl_hits, rtl_misses, rtl_writebacks);

        stats_file_handle = $fopen(GOLDEN_FILE, "r");
        if (stats_file_handle == 0) begin
            $display("WARNING: could not open golden stats file %s - skipping comparison", GOLDEN_FILE);
        end else begin
            scan_count = $fscanf(stats_file_handle, "%d %d %d %d",
                                   golden_accesses, golden_hits, golden_misses, golden_writebacks);
            $fclose(stats_file_handle);

            $display("GOLDEN STATS: accesses=%0d hits=%0d misses=%0d writebacks=%0d",
                       golden_accesses, golden_hits, golden_misses, golden_writebacks);

            if (rtl_hits === golden_hits && rtl_misses === golden_misses &&
                rtl_writebacks === golden_writebacks && rtl_accesses === golden_accesses) begin
                $display("RESULT: PASS - RTL stats match golden model exactly");
            end else begin
                $display("RESULT: FAIL - RTL stats do NOT match golden model");
            end
        end
        $display("----------------------------------------");

        #100;
        $finish;
    end

endmodule